kind: Deployment
apiVersion: apps/v1
metadata:
  name: pulfrmmydkrh
  labels:
    Deploy: pulfrmmydkrh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulfrmmydkrh
  template:
    metadata:
      labels:
        app: pulfrmmydkrh

    spec:
      containers:
      - name: pulfrmmydkrh
        image: akas194/test:v1
        imagePullPolicy: "Always"
        ports:
        - name: http-port
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: sample-sv
spec:
  selector:
    app: pulfrmmydkrh
  type: LoadBalancer
#type: LoadBalancer why is type not required with ingress ?? because ingress is different service. Use NodePort for AWS ALB.
  ports:
  - name: service-port
    port: 80
    targetPort: 80
    protocol: TCP
